### ISSUE TITLE
使用Demo

### ISSUE THREAD

**Issue by tanjie123** [jgchen/brave-dubbo#1]
你好，请问一下，您可不可以提供一个brave-dubbo的使用demo呢？这样可以方便学习

**Comment by shenzhuan** [comment]
BraveFactoryBean这个类都没有
3、dubbo项目快速接入

（1）、项目pom中添加brave-dubbo.jar的依赖，brave-dubbo简化dubbo项目接入zipkin的步骤。

     <dependency>
            <groupId>io.zipkin.brave</groupId>
            <artifactId>brave-dubbo</artifactId>
            <version>1.0.0-SNAPSHOT</version>
        </dependency>
（2）、在spring-application.xml中配置brave

        <bean id="brave" class="com.github.kristofa.brave.dubbo.BraveFactoryBean" p:serviceName="serviceName" p:zipkinHost="http://zipkin-server-ip:9411/" p:rate="1.0" />
说明：

**Comment by lyq628** [comment]
同问一下，可否提供一个完成的例子以方便学习。

**Comment by jinyebing** [comment]
楼上几位大神有成功了嘛？为什么我的springMVC+dubbo 没有成功链起来啊，而且还有一个unknown。有人成功了能分享下源码嘛？
